### ISSUE TITLE
$decimal->toInt() for -INF, INF, NAN give not correct result (zero)

### ISSUE THREAD

**Issue by FoxKeys** [php-decimal/ext-decimal#11]
Hello again.

I have found that $decimal->toInt() return 0 for -INF, INF and NAN.
I suppose, this is wrong. OverflowException seems to be correct for +-INF. And another exception (Invalid_Operation?) for NAN

**Comment by rtheunissen** [comment]
See: https://3v4l.org/oLkmS

Ref: https://github.com/php-decimal/ext-decimal/blob/master/php_decimal.c#L780

**Comment by rtheunissen** [comment]
Leaving this open because I am not convinced that matching PHP behaviour is the right way to go here. Thanks for bringing this up. :+1:

**Comment by FoxKeys** [comment]
I think PHP-way looks not relevant int this case.

You throw OverflowException if the value is greater than PHP_INT_MAX (this seems ok). But, +INF is greater than PHP_INT_MAX. Therefore, +INF must give overfloaw too. Same for -INF, i suppose.

**Comment by rtheunissen** [comment]
This has been fixed in b1e0162446a763edf625d3dc117efaa8095e2854 and released as v1.2.0 :sparkles: 

Throws `RuntimeException` for INF, -INF and NAN.
