### ISSUE TITLE
(new Decimal(-INF))->sqrt() give not correct result (-INF)

### ISSUE THREAD

**Issue by FoxKeys** [php-decimal/ext-decimal#13]
I suppose, it must be or NAN (as PHP sqrt does) or zero (as bcsqrt does)
In any case - sqrt never can be negative, i suppose. Because reverse operation is x*x give always positive result.

**Comment by rtheunissen** [comment]
I think this should be NAN, because we can't represent complex numbers.

**Comment by rtheunissen** [comment]
This has been fixed and released as part of 1.3.0 (along with some opcache-related changes)
