### ISSUE TITLE
Update compare functions and operators to raise an error for uncomparable values (NAN)

### ISSUE THREAD

**Issue by FoxKeys** [php-decimal/ext-decimal#16]
We discussed this in #10 and i suppose, this must affect all comparition functions and operators.
At least, i'm sure about compareTo. "something" can't be more or less than NAN, therefore, comparition can't be -1/0/1 or true/false (for operators) but must raise an Exception.

**Comment by rtheunissen** [comment]
I agree, will update. :+1:

**Comment by rtheunissen** [comment]
Coming back to this @FoxKeys, I'm conflicted. PHP doesn't throw when comparing to NaN, and I'm thinking we should honor that convention here. 

See https://en.wikipedia.org/wiki/NaN#Comparison_with_NaN
