### ISSUE TITLE
Decimal::mod() vs Decimal::rem()

### ISSUE THREAD

**Issue by marcospassos** [php-decimal/ext-decimal#20]
First and foremost, thank you very much for bringing such a valuable library to PHP's world. We decided to drop our Decimal implementation in favour of PHPDecimal and it has proved to be a good decision so far.

I notice that in the docs you say the `Decimal::mod()` is the function that overloads the `%` operator. It is not exactly correct, as the `%` operator performs the [remainder operation](https://en.wikipedia.org/wiki/Remainder) that is not the same as the [modulo operation](https://en.wikipedia.org/wiki/Modulo_operation). As such, `-3 mod 4 = 1` while `-3 % 4 = -3`, however `$minus3->mod(4) == $minus4->rem(4) == -3`. So, `Decimal::mod()` and `Decimal::rem()` are basically aliases here.

Besides fixing the docs about it (I can provide a PR for it :), I'd suggest changing `Decimal::mod()` to perform the modulo operation as it is quite useful.

**Comment by rtheunissen** [comment]
> I notice that in the docs you say the Decimal::mod() is the function that overloads the % operator. It is not exactly correct, as the % operator performs the remainder operation that is not the same as the modulo operation.

The `%` operator is equivalent to the `mod` method - the both invoke the same internal calculation.

```php
use Decimal\Decimal;

print_r((new Decimal("6.5"))->mod("4.25"));
print_r((new Decimal("6.5"))->rem("4.25"));
print_r((new Decimal("6.5") % "4.25"));
```

```text
Decimal\Decimal Object
(
    [value] => 2
    [precision] => 28
)
Decimal\Decimal Object
(
    [value] => 2.25
    [precision] => 28
)
Decimal\Decimal Object
(
    [value] => 2
    [precision] => 28
)
```

> As such, -3 mod 4 = 1

This is not the case in PHP.

```php
$a = -3;
$b =  4;

var_dump($a % $b);
```

```text
int(-3)
```

**Comment by rtheunissen** [comment]
@marcospassos is there still an issue with this?

**Comment by marcospassos** [comment]
No, thank you @rtheunissen!
