### ISSUE TITLE
What is the max number that Decimal can represent?

### ISSUE THREAD

**Issue by giovannialura** [php-decimal/ext-decimal#21]
If I use the float datatype, the limit on 64-bit PHP is 1.8e308

If I use the Int datatype, the limit on 64-bit PHP is 9223372036854775807

What is the limit of the Decimal datatype? 

Thanks in advance.

**Comment by rtheunissen** [comment]
The maximum precision is 425,000,000 for 32-bit and 999,999,999,999,999,999 for 64-bit. That gives you the number of significant figures which could be a very large number or a very small number. The 1.x release does not guard against these limits being reached but I hope to introduce something soon.

Long story short, it is way beyond int max.
