### ISSUE TITLE
Error installing on CentOS 7.6

### ISSUE THREAD

**Issue by ICJR** [php-decimal/ext-decimal#24]
I am receiving the same error that was brought up in a previous issue

`checking for libmpdec library in default path... Could not find libmpdec
configure: error: Please reinstall the libmpdec distribution from http://www.byt                                                                                                                                                             ereef.org/mpdecimal/`

I have the latest version of libmpdec installed by following the instructions listed http://www.bytereef.org/mpdecimal/quickstart.html when I attempt to reinstall I receive the following message 

`Requirement already satisfied: cdecimal in /usr/lib64/python3.6/site-packages`

I also checked the /usr/lib64 folder and I have 

`
/usr/lib64/libmpdec.so
/usr/lib64/libmpdec.so.3
/usr/lib64/libmpdec.so.3.0.0
`

**Comment by ICJR** [comment]
**IGNORE**

It was an issue on my end -_-

**Comment by rtheunissen** [comment]
What was the issue on your end @ICJR ?

**Comment by ICJR** [comment]
I installed mpdecimal + -devel from EPEL but the install of decimal continued to fail, I was told libmpdec could not be found and it was already installed. I believe it was a misconfigured server issue 

_limited experience with python, dedicated server is managed my inmotion. I don't know the exact issue but the extension is installed and working so I am assuming the issue was on my/server end_
