### ISSUE TITLE
Unable to load dynamic library 'php_decimal.dll'

### ISSUE THREAD

**Issue by michaelmlangitan** [php-decimal/ext-decimal#27]
Hello, i could not install the dll file to php in my windows 10.

I already added to "C:\xampp\php\ext" and "extension=php_decimal.dll" in php.ini.
But when i run "php --re decimal" will error :

PHP Warning:  PHP Startup: Unable to load dynamic library 'php_decimal.dll' (tried: C:\xampp\php\ext\php_decimal.dll (The specified module could not be found.), C:\xampp\php\ext\php_php_decimal.dll.dll (The specified module could not be found.)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'php_decimal.dll' (tried: C:\xampp\php\ext\php_decimal.dll (The specified module could not be found.), C:\xampp\php\ext\php_php_decimal.dll.dll (The specified module could not be found.)) in Unknown on line 0
Exception: Extension decimal does not exist

Can anyone help me here?

**Comment by rtheunissen** [comment]
So the .dll file is exactly where it is saying it can't be found?

**Comment by michaelmlangitan** [comment]
yes. i try to looking for php extension directory with my cmd and put there.

cmd:
php -i|findstr extension_dir
result:
extension_dir => C:\xampp\php\ext => C:\xampp\php\ext
the dll:
C:\xampp\php\ext\php_decimal.dll

i use php PHP 7.3.9 (TS) 64bit and i download php_decimal-1.3.0-7.3-ts-vc15-x64.zip

**Comment by rtheunissen** [comment]
I finally managed to test this on a Windows machine and everything worked as expected. Did you figure this out in the meantime?

**Comment by Nevro** [comment]
You need to copy "libmpdec.dll" to "C:\Windows\System32"! That's all.

**Comment by Nevro** [comment]
For Debian/Linux you need to add custom mod with "priority=30" (decimal.so: undefined symbol: php_json_serializable_ce in Unknown on line 0)

sudo nano /etc/php/7.3/mods-available/decimal.ini
`; configuration for php decimal module
; priority=30
extension=decimal.so`

sudo phpenmod decimal
php --re decimal

**Comment by michaelmlangitan** [comment]
finally, i copy "libmpdec.dll" to "C:\Windows\System32" and all work. Thank you so much

**Comment by fd6130** [comment]
> You need to copy "libmpdec.dll" to "C:\Windows\System32"! That's all.

Perhaps this should be mentioned in the docs for Windows user?

**Comment by wimurk** [comment]
Searched for hours. Please keep the docs updated for windows users!!

**Comment by jsanbae** [comment]
> 
That's really helps me.

I my case I had to create the file in /etc/php.d/30-decimal.ini

Thanks!

**Comment by TimexPeachtree** [comment]
> You need to copy "libmpdec.dll" to "C:\Windows\System32"! That's all.

Yes pls mention this for Windows Installation in official docs
