### ISSUE TITLE
Return value of Decimal\Decimal::compareTo() must be of the type int, none returned

### ISSUE THREAD

**Issue by sasokovacic** [php-decimal/ext-decimal#40]
Hi, on my staging server php is throwing the following error

`Return value of Decimal\Decimal::compareTo() must be of the type int, none returned`

and here is the code:

`(new Decimal($value))->compareTo($maxNumber) == -1;`

I'm not getting this error on my laptop

PHP: 7.4.3
Server: Ubuntu 18.04

**Comment by sasokovacic** [comment]
Anyone?

**Comment by rtheunissen** [comment]
I'll take a look at this today 👍🏼

**Comment by sasokovacic** [comment]
Hi @rtheunissen , thanks for your reply. I spent some time on this but figured it out. The extension was not loaded in the php.ini file. Php didn't throw an exception about missing module but about the wrong return type because php final class was actually loaded (it was installed via the composer). I could instantiate an instance but the implementation was missing:

     /**
     * Ordering
     *
     * This method is equivalent to the `<=>` operator.
     *
     * @param mixed $other
     *
     * @return int  0 if this decimal is considered is equal to $other,
     *             -1 if this decimal should be placed before $other,
     *              1 if this decimal should be placed after $other.
     */
    public function compareTo($other): int {}
