### ISSUE TITLE
undefined symbol: php_json_serializable_ce

### ISSUE THREAD

**Issue by syslogic** [php-decimal/ext-decimal#47]
Can build, but then: `undefined symbol: php_json_serializable_ce`.

> PHP Warning:  PHP Startup: Unable to load dynamic library 'decimal.so' (tried: /usr/lib64/php/modules/decimal.so (/usr/lib64/php/modules/decimal.so: undefined symbol: php_json_serializable_ce), /usr/lib64/php/modules/decimal.so.so (/usr/lib64/php/modules/decimal.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

 ---

Loading `json.so` before `decimal.so` seems to help; eg. `/etc/php.d/98-json.ini` and `/etc/php.d/99-decimal.ini`.

**Comment by rtheunissen** [comment]
See https://github.com/php-ds/ext-ds/issues/2

**Comment by syslogic** [comment]
On CentOS/RHEL this works differently than on Ubuntu with these shared libraries. Changing the filename seems to be the only way to affect the loading order (unless loading two modules in one `.ini` file, which seems to be a rather messy configuration).
