### ISSUE TITLE
2.0.0 PECL release has wrong version

### ISSUE THREAD

**Issue by dzuelke** [php-decimal/ext-decimal#49]
Version 2.0.0 is on PECL, and has a stability marked as alpha.

The name should be "2.0.0alpha1" or "2.0.0alpha1", otherwise systems like Composer will treat it as a stable release.

Please delete the release from PECL if at all possible and publish it again.

**Comment by rtheunissen** [comment]
I don't think I can delete the release. I'll upgrade to 2.0.1 stable soon.

**Comment by marcroberts** [comment]
Any update on the 2.0.1 release ?
