### ISSUE TITLE
php 8.0 will be supported?

### ISSUE THREAD

**Issue by reptily** [php-decimal/ext-decimal#55]
now there are errors during compilation

`/tmp/pear/temp/decimal/src/decimal.c: At top level:
/tmp/pear/temp/decimal/src/arginfo.h:65:60: warning: initialization of 'void *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
         {(const char*)(zend_uintptr_t)(required_num_args), ZEND_TYPE_ENCODE_CLASS_CONST(PHP_DECIMAL_RATIONAL_FQCN, 0), 0, 0},
                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/pear/temp/decimal/src/decimal.c:995:1: note: in expansion of macro 'PHP_DECIMAL_ARGINFO_RETURN_RATIONAL'
 PHP_DECIMAL_ARGINFO_RETURN_RATIONAL(Decimal, toRational, 0)
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/pear/temp/decimal/src/arginfo.h:65:60: note: (near initialization for 'php_decimal_arginfo_Decimal_toRational[0].type.ptr')
         {(const char*)(zend_uintptr_t)(required_num_args), ZEND_TYPE_ENCODE_CLASS_CONST(PHP_DECIMAL_RATIONAL_FQCN, 0), 0, 0},
                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/pear/temp/decimal/src/decimal.c:995:1: note: in expansion of macro 'PHP_DECIMAL_ARGINFO_RETURN_RATIONAL'
 PHP_DECIMAL_ARGINFO_RETURN_RATIONAL(Decimal, toRational, 0)
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/pear/temp/decimal/src/arginfo.h:65:60: error: initializer element is not constant
         {(const char*)(zend_uintptr_t)(required_num_args), ZEND_TYPE_ENCODE_CLASS_CONST(PHP_DECIMAL_RATIONAL_FQCN, 0), 0, 0},
                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/pear/temp/decimal/src/decimal.c:995:1: note: in expansion of macro 'PHP_DECIMAL_ARGINFO_RETURN_RATIONAL'
 PHP_DECIMAL_ARGINFO_RETURN_RATIONAL(Decimal, toRational, 0)
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/pear/temp/decimal/src/arginfo.h:65:60: note: (near initialization for 'php_decimal_arginfo_Decimal_toRational[0].type.ptr')
         {(const char*)(zend_uintptr_t)(required_num_args), ZEND_TYPE_ENCODE_CLASS_CONST(PHP_DECIMAL_RATIONAL_FQCN, 0), 0, 0},
                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
`

**Comment by zlodes** [comment]
Issue: #43 
PRs: #53 #54

You can build decimal 1.x from sources of #53, it works.

**Comment by reptily** [comment]
thx!
