### ISSUE TITLE
Testing on php8 with docker

### ISSUE THREAD

**Issue by carlonicora** [php-decimal/ext-decimal#59]
Hello Everyone,

Not an issue di per se (on the contrary, **thanks a lot** for working on the ex-decimal)!
If you are interested in building PHP with ext-decimal support and you use docker, in your PHP Dockerfile just add this:

`RUN mkdir -p /usr/src/php/ext/php-decimal \
    && cd /usr/src/php/ext/php-decimal \
    && git clone https://github.com/php-decimal/ext-decimal.git . \
    && git checkout 1.x-php8 \
    && docker-php-ext-install php-decimal`

and build your docker. There is no need to add `extension=decimal.so` to your php.ini

It works like a charm!

Of course, it relies on the `1.x-php8` branch, which may not be supported for long, but as long as there won't be the updated official package, you can start building and testing

Thanks to the maintainers/supporters of the project!

**Comment by rtheunissen** [comment]
@carlonicora I would like to make this more accessible, could we work on adding a base Dockerfile to the project? It would only be for development and testing purposes. There is a Dockerfile in the 1.x-php8 branch that we could start from.

**Comment by carlonicora** [comment]
Hi @rtheunissen 
Happy to help there. Please keep in mind that every single flavour of docker will have its own differences in the Dockerfile. I mainly use alpine, so the implementation is rather different from the one you have added in the 1.x-php8 branch. One of the reasons is that libmpdec-dev is not natively supported in alpine and has to be compiled.

How would you proceed? A different file, a folder with multiple Dockerfiles?

**Comment by rtheunissen** [comment]
I think we can start out as opinionated as we like, and I think alpine is great. It would be nice to have an easy way change some code and run the tests regardless of the host platform.

**Comment by carlonicora** [comment]
Hi @rtheunissen 

Sorry just seen the message... :(

this is the Dockerfile I use, and it works great.

```
FROM php:8.0-cli-alpine as base

RUN set -xe \
    && apk add --no-cache --virtual .build-deps bash git supervisor curl g++ make autoconf;

ARG MPDECIMAL_VERSION=2.5.1
RUN set -eux; \
	cd /tmp/; \
    curl -sSL -O https://www.bytereef.org/software/mpdecimal/releases/mpdecimal-${MPDECIMAL_VERSION}.tar.gz; \
    tar -xzf mpdecimal-${MPDECIMAL_VERSION}.tar.gz; \
    cd mpdecimal-${MPDECIMAL_VERSION}; \
    ./configure; \
    make; \
    make install;

RUN docker-php-ext-install mysqli bcmath sockets \
    && docker-php-source extract \
    && pecl install decimal \
    && docker-php-source delete \
    && export COMPOSER_PROCESS_TIMEOUT=600 \
    && addgroup -g 1000 -S dockeruser \
    && adduser -u 1000 -S dockeruser -G dockeruser \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
```
