### ISSUE TITLE
error installing version 1.1.0

### ISSUE THREAD

**Issue by rbro** [php-decimal/ext-decimal#6]
First, thank you for creating this extension.  I have used bcmath extensively and am looking forward to trying out this new extension.

I am running on CentOS 7.5.  I was able to install version 1.0.1 with PECL, but getting an error installing 1.1.0:

```
checking for libmpdec library in default path... Could not find libmpdec
configure: error: Please reinstall the libmpdec distribution from http://www.bytereef.org/mpdecimal/
```

When I install 1.0.1, I get:

```
checking for libmpdec files in default path... found in /usr
```

I installed mpdecimal and mpdecimal-devel from EPEL (https://fedoraproject.org/wiki/EPEL).  I have these files in /usr/lib64:

```
/usr/lib64/libmpdec.so
/usr/lib64/libmpdec.so.2
/usr/lib64/libmpdec.so.2.4.2
```

Please let me know if I can provide more information to help reproduce this.

Thanks for your help.

**Comment by rtheunissen** [comment]
@remicollet do you know if there is a way to also check that directory without hard-coding it? I'm also wondering if you can set the libmpdec path using `--with-libmpdec-path`?

**Comment by remicollet** [comment]
> I am running on CentOS 7.5.

@rbro  So you should use my repository which provide this extension among some others ;)
https://blog.remirepo.net/pages/PECL-extensions-RPM-status
And all PHP versions (5.4 to 7.3)

You have to build the extension using --with-libdir=lib64

@rtheunissen I don't see clean way. Perhaps adding 

```
      elif test -r $i/lib64/libmpdec.$SHLIB_SUFFIX_NAME || test -r $i/lib64/libmpdec.a; then
        LIBMPDEC_DIR=$i/lib64
        LIBMPDEC_INC=$i/include
        AC_MSG_RESULT(found in $LIBMPDEC_DIR)
        break

```

**Comment by rtheunissen** [comment]
I'll update the "install" docs so that it is more clear, and will link to your repo @remicollet. :100:

**Comment by rtheunissen** [comment]
I wish there was a platform-independent way of saying "find this library please".

**Comment by rbro** [comment]
Thanks, I've looked into installing PHP from RPM's, but because I have a bunch of various configure options, I've always compiled PHP manually.

Could checking in /usr/lib64 be added?  Or is there a way to install a package with PECL and pass configure options?  I have other PECL modules installed and haven't run into this for those.  Thanks again for your help.

**Comment by remicollet** [comment]
> because I have a bunch of various configure 

Out of topic here, BTW, will be curious to see which ones

See PR #7 which includes changes from my previous comment

**Comment by remicollet** [comment]
@rtheunissen I was thiking about having the right default value for PHP_LIBDIR, but this doesn't seems a good idea.

* Manually installed libraries use "lib", manually build extension also use "lib", this seems consistent
* Packaged libraries use "lib64", and package extension are aware of this and use --with-libdir with the proper value

Issue is for people trying to run manual build of some piece and packages for other pieces, which , IMHO is a bad idea

**Comment by rbro** [comment]
@remicollet Thanks, let me know if there's a better place to discuss this.  When I looked the other day, I noticed the php rpm includes mod_php, which I don't need, but looking more today, is the php package optional?  Could I install just php-cli and php-fpm and skip php?

My configure line is below.  Could I get to something close to this?  Just trying to avoid extra libraries as much as possible.

```
./configure \
  --enable-bcmath \
  --enable-fpm \
  --enable-intl \
  --enable-mbstring \
  --enable-pcntl \
  --enable-soap \
  --enable-sockets \
  --enable-sysvsem \
  --enable-sysvshm \
  --enable-zip \
  --with-curl \
  --with-freetype-dir \
  --with-gd \
  --with-gettext \
  --with-gmp \
  --with-imap \
  --with-imap-ssl \
  --with-jpeg-dir \
  --with-kerberos \
  --with-ldap \
  --with-libdir=lib64 \
  --with-mysqli \
  --with-openssl \
  --with-pdo-dblib \
  --with-pdo-mysql \
  --with-readline \
  --with-xsl \
  --with-zlib
```

**Comment by remicollet** [comment]
> a better place to discuss this.

https://forum.remirepo.net/
https://github.com/remicollet/remirepo/issues
https://blog.remirepo.net/post/2012/09/03/remirepo-IRC-channel-on-freenode-network
etc

> is the php package optional?

Yes

> My configure line is below. Could I get to something close to this? Just trying to avoid extra libraries as much as possible.

Yes, all extensions are available, most of them build shared, so can install only the needed ones.

Nothing special in your configure line.
