### ISSUE TITLE
Serialize as number instead of as string with json_encode

### ISSUE THREAD

**Issue by patrickvuarnoz** [php-decimal/ext-decimal#65]
When using json_encode on a decimal it outputs the value as a string instead of as a number. It's easiest to explain it in an example:
```
echo json_encode(["decimal" => new Decimal("0.1")]);
```

Actual output looks like this:
```
{"decimal":"0.1"}
```

Expected would be:
```
{"decimal":0.1}
```

From the JSON perspective it is strange to transport a decimal as a string since JSON itself is already a string. According to JSON Schema you would define a decimal as { "type": "number" } which does not allow numbers as strings. See: https://json-schema.org/understanding-json-schema/reference/numeric.html#number

I'm aware that in Javascript we have the same double / float precision issues as in PHP, but:
- If I receive a number as string in Javascript and do some math with it (like "0.1" + 0.2), it will perform a string operation and will return an odd result ("0.10.2")
- It should be up to the receiving party of a JSON to deal with precision issues when interpreting JSON, i.e. by using a similar library as php-decimal in the client if required

Is there any chance that this behaviour of php-decimal can be fixed or at least be configured?

**Comment by patrickvuarnoz** [comment]
After playing around with a wrapper and with json_encode I realize that there is probably not an easy solution to that problem since values have to be converted to native data types prior to json_encode (i.e. in jsonSerialize). That means we're back to floats and their problems. 

In PHP there's a setting for serialize_precision. If set to -1 it behaves quite smart and handles the number rather well in the json_encode serialization. So outputting a decimal as float in jsonSerialize in combination with serialize_precision=-1 lead to useful results for us. 

See https://www.php.net/manual/en/ini.core.php#ini.serialize-precision.

**Comment by rtheunissen** [comment]
I've been thinking about this a lot. Something we should make sure we get right is that serializing to JSON and back again should return to the original value, but that is not the case anyway since we have to convert it to a string.

The best we can do is make sure we preserve the _value_ as best we can, and I think the conversion to float will inevitably change the information encoded in the decimal type. Using a string preserves the value exactly, so for now that's probably the best type to use.

**Comment by patrickvuarnoz** [comment]
I understand the reasoning behind serializing a decimal as string – it's the same that PDO/MySQL does by default. 

But dealing with strings for decimals in JSON causes side effects and headaches in many clients that consume that JSON and prevents us from using a proper JSON Schema. In PHP itself it's not a big issue if you json_decode() a JSON which contains strings for decimals. It will just read them as strings and with PHP's type juggling it will automatically use the value as float if you do math with it. But also in PHP it will cast it as _float_ if you forget to convert that string to a decimal first, which then does not preserve the value.

I think the only real solution would be that php-decimal created it's own json_encode and json_decode methods that override the original methods (if that's even possible) or exist as php-decimals own alternatives.

In your own json_encode() you could detect the decimal class and encode it as `{ "decimal": 3.1415 }` (without quotes) and in your own json_decode() you could detect and decode such a value back to `new Decimal("3.1415", 4)`. This would be a very proper way of dealing with JSON and preserving the values.

**Comment by rtheunissen** [comment]
> But dealing with strings for decimals in JSON causes side effects and headaches in many clients that consume that JSON and prevents us from using a proper JSON Schema.

I'd like to understand more about the side-effects and headaches here. If the client knows to expect a string decimal for that field, the client can decode/normalize it as such. If the client's language happens to concatenate a string and number, that's on the client.

If your use case requires a float as the JSON representation of a decimal, it seems like the best approach is to compose your own decimal type around the extension and implement jsonSerialize there.

We could consider things like ini settings but going down that route makes the code more difficult to reason with and analyze.

**Comment by rtheunissen** [comment]
Just to summarize, I think this is a decoding concern, and therefore not a responsibility of this library. I understand how it might be inconvenient to the client in some cases. I believe this is also how Python does it, using the same internal decimal library and extended options for decoding.

**Comment by patrickvuarnoz** [comment]
I think the side-effects and headaches I see are the following:

1. We cannot create a proper JSON schema for our REST API. We have to declare decimals as strings instead of numbers. That means that every other content can theoretically be provided in those strings since the schema only specifies the property as string. We use the same schema for receiving data by the client and there the JSON schema validation cannot be properly used. It requires an additional/separate validation step just for the decimal properties.
2. Every developer that uses our API has to be aware of the fact that we send decimals as strings, which is not really intuitive and has to be mentioned very explicitly in our documentation. 
3. Every developer that uses our API cannot use the default de-serialization of the JSON data but has to add an extra step that transforms those decimal strings to whatever data type is best for them. For example in JS if you receive JSON data it is normally de-serialized automatically by your framework. Here you would have to loop over all received records and transform the decimals to floats if you want to do math with them (e.g. build sums or such). That's a lot of additional work for _every_ developer that consumes the API. 
4. If a developer forgets to transform those decimal strings to floats (or decimal if that's available in their language) it can cause side-effects. In Javascript, if you receive [{ "amount": "100.01" }, { "amount": "200.02" }] and try to build the sum of the amounts, you'd end up getting "100.01200.02" instead of 300.03. Such side-effects might be hard to identify since they can happen somewhere else in yor code.

If we could transfer decimal values in JSON as { "amount": 100.01 } all this would not be an issue. Of course, a client might loose the decimal precision if his language/framework de-serializes the values as floats. But for such instances the developer could still use/implement a different de-serialization to counteract the problem, if this decimal precision in the client is really required.

In the end it's a trade-off. For me the advantages of transferring decimals as { "amount": 100.01 } instead of { "amount": "100.01" } clearly outweigh the potential disadvantages. But other developers should express their opinions as well.

Concerning a custom version of json_encode() and json_decode() that would deal with the serialization and de-serialization as proposed – I agree that this is not really a problem of php-decimal and maybe it's better to not tie it to php-decimal. Instead it would be if we had some kind of new json_encode() and json_decode() that could work with type hints or class maps so that it would be possible to serialize and deserialize data for a wider range of special data types and structs.

For the time being we're going to use the approach with serialize_precision=-1 and use floats in JSON.

**Comment by rtheunissen** [comment]
> 1. We cannot create a proper JSON schema for our REST API. We have to declare decimals as strings instead of numbers. That means that every other content can theoretically be provided in those strings since the schema only specifies the property as string. 

Could you use a regex pattern in the schema definition to make sure it's a valid decimal? 


> 2. Every developer that uses our API has to be aware of the fact that we send decimals as strings, which is not really intuitive and has to be mentioned very explicitly in our documentation. 

For what it's worth, in my experience it is common to see decimals as strings in JSON, such as latitude/longitude, price (unless it's an integer in cents), benchmark results etc. It's true that the client has to parse it before they can do calculations with it though yes. 


> 3. Every developer that uses our API cannot use the default de-serialization of the JSON data but has to add an extra step that transforms those decimal strings to whatever data type is best for them. For example in JS if you receive JSON data it is normally de-serialized automatically by your framework. Here you would have to loop over all received records and transform the decimals to floats if you want to do math with them (e.g. build sums or such). That's a lot of additional work for _every_ developer that consumes the API. 

If the precision is important, there is no way around this. Should be simple enough for the client to parse as they loop and test their code. 

> 4. If we could transfer decimal values in JSON as { "amount": 100.01 } all this would not be an issue. Of course, a client might loose the decimal precision if his language/framework de-serializes the values as floats. But for such instances the developer could still use/implement a different de-serialization to counteract the problem, if this decimal precision in the client is really required.

Once that information is lost there is no way for the client to error-correct. 

> In the end it's a trade-off. For me the advantages of transferring decimals as { "amount": 100.01 } instead of { "amount": "100.01" } clearly outweigh the potential disadvantages. But other developers should express their opinions as well.

The most important thing here is to preserve the value - I don't think this library would ever by-default serialize decimals as float. 

 
> Concerning a custom version of json_encode() and json_decode() that would deal with the serialization and de-serialization as proposed – I agree that this is not really a problem of php-decimal and maybe it's better to not tie it to php-decimal. Instead it would be if we had some kind of new json_encode() and json_decode() that could work with type hints or class maps so that it would be possible to serialize and deserialize data for a wider range of special data types and structs.

What we could do is have Decimal\json_encode and decode with the same signature, supporting some new constants like ENCODE_DECIMAL_AS_FLOAT and DECODE_DECIMAL_TO_FLOAT that takes care of the conversion for you, and just pass through to the general JSON functions. 

Is that what you were envisioning? 

Unfortunately I don't think we can replace that base function itself.

**Comment by patrickvuarnoz** [comment]
Thanks for your detailed answer. Yes, I could use regex for the validation, but it's only part of the problem.

If you were to add `Decimal\json_encode` and `Decimal\json_decode` I would think of the following options. Please note that I'm using the JSON schema types on one side and the PHP types on the other side to make it more clear what is encoded/decoded from what to what.

*Encoding*

* ENCODE_DECIMALS_AS_STRINGS: Encoding `(object)["value" => new Decimal("1.2345")]` as `{ "value": "1.2345" }`, the current default
* ENCODE_DECIMALS_AS_NUMBERS: Encoding `(object)["value" => new Decimal("1.2345")]` as `{ "value": 1.2345 }`, my desired outcome
* ENCODE_FLOATS_AS_STRINGS: Might be required
* ENCODE_FLOATS_AS_NUMBERS: Might be required

*Decoding*

* DECODE_NUMBERS_AS_DECIMALS: Decoding `{ "value": 1.2345 }` as `(object)["value" => new Decimal("1.2345")]`, my desired outcome
* DECODE_NUMBERS_AS_FLOATS: Decoding `{ "value": 1.2345 }` as `(object)["value" => (float)"1.2345"]`, probably a must option
* DECODE_STRINGS_AS_DECIMALS: Decoding `{ "value": "1.2345" }` as `(object)["value" => new Decimal("1.2345")]`, would be required if ENCODE_DECIMALS_AS_STRINGS was used for encoding to make it reversible

The option DECODE_STRINGS_AS_DECIMALS might be a tiny bit problematic because it's a global setting for decoding a whole dataset. A regex like `/"(-)?[0-9]+\.[0-9]+"/` (simplified) to check whether a JSON string looks like a decimal might also match other strings that were not intended to be decoded as decimal. Having them converted to decimals instead of strings could have side effects – although this is probably an edge case.

I'm just mentioning it because the global JSON_NUMERIC_CHECK in `json_encode()` has a similar problematic aspect of converting strings to numbers/integers. For example a phone number like "0041999999999" will be converted to the number 41999999999. JSON_NUMERIC_CHECK would have worked for us in conjunction with php-decimal hadn't it that problem.
