### ISSUE TITLE
Documentation not available anymore: php-decimal.io

### ISSUE THREAD

**Issue by ndberg** [php-decimal/ext-decimal#76]
Thanks for this great project.

I just wanted to report, that the php-decimal.io Site is not available anymore.

**Comment by fd6130** [comment]
> Thanks for this great project.
> 
> I just wanted to report, that the php-decimal.io Site is not available anymore.

Same, and I found that they changed to this link already: https://php-decimal.github.io/#introduction

**Comment by rtheunissen** [comment]
As far as I can tell, all sites have been updated to reference Github pages.
I could no longer justify spending $100+ every year on the .io domain.
